defaults:
    target:
        host: expired.badssl.com
        scheme: https

Sections:
    website:
        rules:
            - ValidSslCertificate
            - HttpHeaderXSSProtectionSecure
            - HttpHeaderExposeLanguage
            - HttpHeaderContentTypeNoSniffing
            - HttpHeaderCookieWithHttpOnlyFlag
            - HttpHeaderHSTSPresent
            - HttpHeaderHSTSWithSubdomains
            - HttpHeaderCookieWithHttpSecureFlag
