defaults:
    target:
        host: ~

Sections:
    website:
        rules:
            - HttpRequestTime:
                max: 1500
            - TitleTagLength
            - MetaDescriptionLength
            - OGPropertyPresent
            - TwitterProperty
            - LinkRelCanonical
            - LinkHrefLang
            - AppleTouchIcon
            - MetaGeneratorNotPresent
            - H1TagPresent