defaults:
    target:
        host: ~

Sections:
    website:
        rules:
            - HttpRequestTime:
                - ["maxTransferTime", 1500]
            - TitleTagLength
            - MetaDescriptionLength
            - OGPropertyPresent
            - TwitterProperty
            - LinkRelCanonical
            - LinkHrefLang
            - AppleTouchIcon
            - MetaGeneratorNotPresent